//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
// //   title: "Create Next App",
//    description: "Generated by create next app",
//  };

// src/app/layout.tsx
// src/app/layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Format date as February 03, 2025
  const currentDate = "February 03, 2025";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased print:bg-white print:text-black`}>
        {children}
        <div className="print-footer no-screen">
          <div className="print-footer-left">Portfolio Dashboard - Yahya Chaker</div>
          <div className="print-footer-right">{currentDate}</div>
        </div>
      </body>
    </html>
  );
}